[package]
name = "pi_wgpu"
version = "0.1.0"
authors = ["moyy <myy412001799@gmail.com>"]
edition = "2021"
description = "WebGPU implement"
repository = "https://github.com/GaiaWorld/pi_wgpu"
license = "MIT OR Apache-2.0"
keywords = ["pi", "webgpu"]

[features]
default = ["gl"]
gl = ["naga/glsl-out", "glow", "egl", "libloading"]

[dependencies]
log = "0.4"
futures = "0.3"
bitflags = "2.3"
thiserror = "1.0"
lazy_static = "1.4"
parking_lot = "0.12"
raw-window-handle = "0.5"
static_assertions = "1.1"
tracing = { version = "0.1", default-features = false, features = ["std"] }

# pi dependencies
pi_share = "0.4"

# wgpu
wgt = { package = "wgpu-types", version = "0.15" }

# backend: Gles
glow = { version = "0.12.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egl = { package = "khronos-egl", version = "4.1", features = ["dynamic"], optional = true }
libloading = { version = "0.7", optional = true }

[target.'cfg(target_os = "emscripten")'.dependencies]
egl = { package = "khronos-egl", version = "4.1", features = ["static", "no-pkg-config"] }
#Note: it's unused by emscripten, but we keep it to have single code base in egl.rs
libloading = { version = "0.7", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["profileapi", "libloaderapi", "windef", "winuser", "dcomp"] }
native = { package = "d3d12", version = "0.6.0", git = "https://github.com/gfx-rs/d3d12-rs", rev = "b940b1d71", features = ["libloading"], optional = true }

[target.'cfg(any(target_os="macos", target_os="ios"))'.dependencies]
mtl = { package = "metal", version = "0.24.0" }
objc = "0.2.5"
core-graphics-types = "0.1"

[target.'cfg(all(target_arch = "wasm32", not(target_os = "emscripten")))'.dependencies]
web-sys = { version = "0.3.61", features = ["Window", "HtmlCanvasElement", "WebGl2RenderingContext", "OffscreenCanvas"] }
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
android_system_properties = "0.1.1"

[dependencies.naga]
git = "https://github.com/gfx-rs/naga"
rev = "f0edae8"
version = "0.11"
features = ["clone"]

# DEV dependencies

[dev-dependencies]
winit = "0.27"
pollster = "0.3"
env_logger = "0.10"

[dev-dependencies.naga]
git = "https://github.com/gfx-rs/naga"
rev = "f0edae8"
version = "0.11"
features = ["wgsl-in"]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
glutin = "0.29.1" # for "gles" example
